# Generated by Django 4.1.6 on 2023-02-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeakub', '0007_profile_postcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.TextField()),
            ],
        ),
    ]
