# Generated by Django 4.1.6 on 2023-02-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeakub', '0008_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_name',
            field=models.TextField(unique=True),
        ),
    ]
